name: edory_app
description: Edory - KI-gestützte Storytelling-Plattform für Kinder und Familien
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.5
  
  # Navigation
  go_router: ^16.2.0
  
  # HTTP Client
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Design
  flutter_animate: ^4.2.0+1
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  
  # Utils
  equatable: ^2.0.5
  uuid: ^4.1.0
  intl: ^0.20.2
  dartz: ^0.10.1
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Accessibility
  flutter_tts: ^4.2.3
  
  # Animations
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Testing
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  # Enable web and desktop platforms
  # Run `flutter create . --platforms=web,windows,android,ios` to enable all platforms
  
  # Assets commented out for initial testing
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  
  # Fonts will be added later
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
