// <auto-generated />
using System;
using Edory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edory.Infrastructure.Migrations
{
    [DbContext(typeof(EdoryDbContext))]
    [Migration("20250820121831_CurrentDatabaseState")]
    partial class CurrentDatabaseState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edory.Character.Domain.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AdoptionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorFamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Characters_CreatedAt");

                    b.HasIndex("CreatorFamilyId")
                        .HasDatabaseName("IX_Characters_CreatorFamilyId");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_Characters_IsPublic");

                    b.ToTable("Characters", null, t =>
                        {
                            t.HasCheckConstraint("CK_Characters_AgeRange", "MinAge >= 0 AND MaxAge >= MinAge AND MaxAge <= 18");

                            t.HasCheckConstraint("CK_Characters_BaseCourage", "BaseCourage >= 0 AND BaseCourage <= 100");

                            t.HasCheckConstraint("CK_Characters_BaseCreativity", "BaseCreativity >= 0 AND BaseCreativity <= 100");

                            t.HasCheckConstraint("CK_Characters_BaseCuriosity", "BaseCuriosity >= 0 AND BaseCuriosity <= 100");

                            t.HasCheckConstraint("CK_Characters_BaseEmpathy", "BaseEmpathy >= 0 AND BaseEmpathy <= 100");

                            t.HasCheckConstraint("CK_Characters_BaseHelpfulness", "BaseHelpfulness >= 0 AND BaseHelpfulness <= 100");

                            t.HasCheckConstraint("CK_Characters_BaseHumor", "BaseHumor >= 0 AND BaseHumor <= 100");

                            t.HasCheckConstraint("CK_Characters_BasePersistence", "BasePersistence >= 0 AND BasePersistence <= 100");

                            t.HasCheckConstraint("CK_Characters_BaseWisdom", "BaseWisdom >= 0 AND BaseWisdom <= 100");
                        });
                });

            modelBuilder.Entity("Edory.Character.Domain.CharacterInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseAppearance")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BaseDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("BaseMaxAge")
                        .HasColumnType("integer");

                    b.Property<int>("BaseMinAge")
                        .HasColumnType("integer");

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BasePersonality")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("BaseTraitsCourage")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsCreativity")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsCuriosity")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsEmpathy")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsHelpfulness")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsHumor")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsPersistence")
                        .HasColumnType("integer");

                    b.Property<int>("BaseTraitsWisdom")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentCourage")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCreativity")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentCuriosity")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentEmpathy")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHelpfulness")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHumor")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentPersistence")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWisdom")
                        .HasColumnType("integer");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ExperienceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OriginalCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerFamilyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaseName")
                        .HasDatabaseName("IX_CharacterInstances_BaseName");

                    b.HasIndex("LastInteractionAt")
                        .HasDatabaseName("IX_CharacterInstances_LastInteractionAt");

                    b.HasIndex("OriginalCharacterId")
                        .HasDatabaseName("IX_CharacterInstances_OriginalCharacterId");

                    b.HasIndex("OwnerFamilyId")
                        .HasDatabaseName("IX_CharacterInstances_OwnerFamilyId");

                    b.HasIndex("OwnerFamilyId", "LastInteractionAt")
                        .HasDatabaseName("IX_CharacterInstances_Family_LastInteraction");

                    b.ToTable("CharacterInstances", null, t =>
                        {
                            t.HasCheckConstraint("CK_CharacterInstances_AgeRange", "BaseMinAge >= 0 AND BaseMaxAge >= BaseMinAge AND BaseMaxAge <= 18");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsCourage", "BaseTraitsCourage >= 0 AND BaseTraitsCourage <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsCreativity", "BaseTraitsCreativity >= 0 AND BaseTraitsCreativity <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsCuriosity", "BaseTraitsCuriosity >= 0 AND BaseTraitsCuriosity <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsEmpathy", "BaseTraitsEmpathy >= 0 AND BaseTraitsEmpathy <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsHelpfulness", "BaseTraitsHelpfulness >= 0 AND BaseTraitsHelpfulness <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsHumor", "BaseTraitsHumor >= 0 AND BaseTraitsHumor <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsPersistence", "BaseTraitsPersistence >= 0 AND BaseTraitsPersistence <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_BaseTraitsWisdom", "BaseTraitsWisdom >= 0 AND BaseTraitsWisdom <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentCourage", "CurrentCourage >= 0 AND CurrentCourage <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentCreativity", "CurrentCreativity >= 0 AND CurrentCreativity <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentCuriosity", "CurrentCuriosity >= 0 AND CurrentCuriosity <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentEmpathy", "CurrentEmpathy >= 0 AND CurrentEmpathy <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentHelpfulness", "CurrentHelpfulness >= 0 AND CurrentHelpfulness <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentHumor", "CurrentHumor >= 0 AND CurrentHumor <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentPersistence", "CurrentPersistence >= 0 AND CurrentPersistence <= 100");

                            t.HasCheckConstraint("CK_CharacterInstances_CurrentWisdom", "CurrentWisdom >= 0 AND CurrentWisdom <= 100");
                        });
                });

            modelBuilder.Entity("Edory.Memory.Domain.CharacterMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_instance_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fragments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fragments");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CharacterInstanceId")
                        .HasDatabaseName("ix_character_memories_character_instance_id");

                    b.HasIndex("LastUpdatedAt")
                        .HasDatabaseName("ix_character_memories_last_updated");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_character_memories_type");

                    b.HasIndex("CharacterInstanceId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_character_memories_character_instance_type");

                    b.ToTable("character_memories", (string)null);
                });

            modelBuilder.Entity("Edory.Character.Domain.Character", b =>
                {
                    b.OwnsOne("Edory.SharedKernel.ValueObjects.CharacterDna", "Dna", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Appearance")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Appearance");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Description");

                            b1.Property<int>("MaxAge")
                                .HasColumnType("integer")
                                .HasColumnName("MaxAge");

                            b1.Property<int>("MinAge")
                                .HasColumnType("integer")
                                .HasColumnName("MinAge");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.Property<string>("Personality")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Personality");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");

                            b1.OwnsOne("Edory.SharedKernel.ValueObjects.CharacterTraits", "BaseTraits", b2 =>
                                {
                                    b2.Property<Guid>("CharacterDnaCharacterId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Courage")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseCourage");

                                    b2.Property<int>("Creativity")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseCreativity");

                                    b2.Property<int>("Curiosity")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseCuriosity");

                                    b2.Property<int>("Empathy")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseEmpathy");

                                    b2.Property<int>("Helpfulness")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseHelpfulness");

                                    b2.Property<int>("Humor")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseHumor");

                                    b2.Property<int>("Persistence")
                                        .HasColumnType("integer")
                                        .HasColumnName("BasePersistence");

                                    b2.Property<int>("Wisdom")
                                        .HasColumnType("integer")
                                        .HasColumnName("BaseWisdom");

                                    b2.HasKey("CharacterDnaCharacterId");

                                    b2.ToTable("Characters");

                                    b2.WithOwner()
                                        .HasForeignKey("CharacterDnaCharacterId");
                                });

                            b1.Navigation("BaseTraits")
                                .IsRequired();
                        });

                    b.Navigation("Dna")
                        .IsRequired();
                });

            modelBuilder.Entity("Edory.Character.Domain.CharacterInstance", b =>
                {
                    b.HasOne("Edory.Character.Domain.Character", null)
                        .WithMany()
                        .HasForeignKey("OriginalCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
